name: "First Test"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "terraform testing"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.5.4"  # Replace with your desired Terraform version

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{secrets.AWS_BUCKET_NAME}}" -backend-config="key=${{secrets.AWS_BUCKET_KEY_NAME}}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Plan
        if: ${{ github.event_name == 'push' }}
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Terraform Plan Status
        if: ${{ failure() }}
        run: echo "Terraform plan failed, check your code." && exit 1

      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: terraform apply -auto-approve tfplan
        continue-on-error: true

      - name: Terraform Destroy
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}  # Change the condition based on when you want to trigger the destroy
        run: terraform destroy -auto-approve
